config/routes.rb
Rails.application.routes.draw do
  resources :apartments
  resources :floors
  resources :builds
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/apartment.rb
class Apartment < ApplicationRecord
  belongs_to :floor
  belongs_to :build
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/build.rb
class Build < ApplicationRecord
  has_many :floors
  has_many :apartments, :through => :floors
end

app/models/floor.rb
class Floor < ApplicationRecord
  has_many :apartments
  belongs_to :build
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]

  # GET /apartments
  # GET /apartments.json
  def index
    @apartments = Apartment.all
  end

  # GET /apartments/1
  # GET /apartments/1.json
  def show
  end

  # GET /apartments/new
  def new
    @apartment = Apartment.new
  end

  # GET /apartments/1/edit
  def edit
  end

  # POST /apartments
  # POST /apartments.json
  def create
    @apartment = Apartment.new(apartment_params)

    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1
  # PATCH/PUT /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to @apartment, notice: 'Apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartment_params
      params.require(:apartment).permit(:gate_number, :floor_id, :build_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  before_action :set_build, only: [:show, :edit, :update, :destroy]

  # GET /builds
  # GET /builds.json
  def index
    @builds = Build.all
  end

  # GET /builds/1
  # GET /builds/1.json
  def show
  end

  # GET /builds/new
  def new
    @build = Build.new
  end

  # GET /builds/1/edit
  def edit
  end

  # POST /builds
  # POST /builds.json
  def create
    @build = Build.new(build_params)

    respond_to do |format|
      if @build.save
        format.html { redirect_to @build, notice: 'Build was successfully created.' }
        format.json { render :show, status: :created, location: @build }
      else
        format.html { render :new }
        format.json { render json: @build.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /builds/1
  # PATCH/PUT /builds/1.json
  def update
    respond_to do |format|
      if @build.update(build_params)
        format.html { redirect_to @build, notice: 'Build was successfully updated.' }
        format.json { render :show, status: :ok, location: @build }
      else
        format.html { render :edit }
        format.json { render json: @build.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /builds/1
  # DELETE /builds/1.json
  def destroy
    @build.destroy
    respond_to do |format|
      format.html { redirect_to builds_url, notice: 'Build was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_build
      @build = Build.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def build_params
      params.require(:build).permit(:name)
    end
end

app/controllers/floors_controller.rb
class FloorsController < ApplicationController
  before_action :set_floor, only: [:show, :edit, :update, :destroy]

  # GET /floors
  # GET /floors.json
  def index
    @floors = Floor.all
  end

  # GET /floors/1
  # GET /floors/1.json
  def show
  end

  # GET /floors/new
  def new
    @floor = Floor.new
  end

  # GET /floors/1/edit
  def edit
  end

  # POST /floors
  # POST /floors.json
  def create
    @floor = Floor.new(floor_params)

    respond_to do |format|
      if @floor.save
        format.html { redirect_to @floor, notice: 'Floor was successfully created.' }
        format.json { render :show, status: :created, location: @floor }
      else
        format.html { render :new }
        format.json { render json: @floor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /floors/1
  # PATCH/PUT /floors/1.json
  def update
    respond_to do |format|
      if @floor.update(floor_params)
        format.html { redirect_to @floor, notice: 'Floor was successfully updated.' }
        format.json { render :show, status: :ok, location: @floor }
      else
        format.html { render :edit }
        format.json { render json: @floor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /floors/1
  # DELETE /floors/1.json
  def destroy
    @floor.destroy
    respond_to do |format|
      format.html { redirect_to floors_url, notice: 'Floor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_floor
      @floor = Floor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def floor_params
      params.require(:floor).permit(:floor_number, :build_id)
    end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/helpers/floors_helper.rb
module FloorsHelper
end

app/views/apartments/_form.html.erb
<%= simple_form_for(@apartment) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :gate_number %>
    <%= f.association :floor, label_method: :floor_number %>
    <%= f.association :build %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/apartments/edit.html.erb
<h1>Editing Apartment</h1>

<%= render 'form', apartment: @apartment %>

<%= link_to 'Show', @apartment %> |
<%= link_to 'Back', apartments_path %>

app/views/apartments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Apartments</h1>

<table>
  <thead>
    <tr>
      <th>Gate number</th>
      <th>Floor</th>
      <th>Build</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apartments.each do |apartment| %>
      <tr>
        <td><%= apartment.gate_number %></td>
        <td><%= apartment.floor.floor_number %></td>

        <td><%= apartment.build.name %></td>
        <td><%= link_to 'Show', apartment %></td>
        <td><%= link_to 'Edit', edit_apartment_path(apartment) %></td>
        <td><%= link_to 'Destroy', apartment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Apartment', new_apartment_path %>

app/views/apartments/new.html.erb
<h1>New Apartment</h1>

<%= render 'form', apartment: @apartment %>

<%= link_to 'Back', apartments_path %>

app/views/apartments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Gate number:</strong>
  <%= @apartment.gate_number %>
</p>
<p>
  <strong>Floor:</strong>
  <%= @apartment.floor.floor_number %>
</p>
<p>
  <strong>Build:</strong>
  <%= @apartment.build.name %>
</p>


<%= link_to 'Edit', edit_apartment_path(@apartment) %> |
<%= link_to 'Back', apartments_path %>

app/views/builds/_form.html.erb
<%= simple_form_for(@build) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/builds/edit.html.erb
<h1>Editing Build</h1>

<%= render 'form', build: @build %>

<%= link_to 'Show', @build %> |
<%= link_to 'Back', builds_path %>

app/views/builds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Builds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @builds.each do |build| %>
      <tr>
        <td><%= build.name %></td>
        <td><%= link_to 'Show', build %></td>
        <td><%= link_to 'Edit', edit_build_path(build) %></td>
        <td><%= link_to 'Destroy', build, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Build', new_build_path %>

app/views/builds/new.html.erb
<h1>New Build</h1>

<%= render 'form', build: @build %>

<%= link_to 'Back', builds_path %>

app/views/builds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @build.name %>
</p>

<%= link_to 'Edit', edit_build_path(@build) %> |
<%= link_to 'Back', builds_path %>

app/views/floors/_form.html.erb
<%= simple_form_for(@floor) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :floor_number %>
    <%= f.association :build %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/floors/edit.html.erb
<h1>Editing Floor</h1>

<%= render 'form', floor: @floor %>

<%= link_to 'Show', @floor %> |
<%= link_to 'Back', floors_path %>

app/views/floors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Floors</h1>

<table>
  <thead>
    <tr>
      <th>Floor number</th>
      <th>Build</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @floors.each do |floor| %>
      <tr>
        <td><%= floor.floor_number %></td>
        <td><%= floor.build.name %></td>
        <td><%= link_to 'Show', floor %></td>
        <td><%= link_to 'Edit', edit_floor_path(floor) %></td>
        <td><%= link_to 'Destroy', floor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Floor', new_floor_path %>

app/views/floors/new.html.erb
<h1>New Floor</h1>

<%= render 'form', floor: @floor %>

<%= link_to 'Back', floors_path %>

app/views/floors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Floor number:</strong>
  <%= @floor.floor_number %>
</p>
<p>
  <strong>Build:</strong>
  <%= @floor.build.name %>
</p>
<%= link_to 'Edit', edit_floor_path(@floor) %> |
<%= link_to 'Back', floors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BuildApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>